name: Android application

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Prepare java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Cache clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
            .cpcache
          key: ${{ runner.os }}-cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: ${{ runner.os }}-cljdeps-

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: 1.12.3.1577

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

      - name: Build android app
        env:
            KEYSTOREALIAS_PASS: ${{ secrets.ANDROID_KEYSTOREALIAS_PASS }}
            KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
            KEYSTOREALIAS: ${{ secrets.ANDROID_KEYSTOREALIAS }}
            KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
        run: |
            echo "$KEYSTORE" | base64 --decode > android/official.jks
            npx cap sync
            npx cap build android --keystorepath official.jks \
                                  --keystorepass "$KEYSTORE_PASS" \
                                  --keystorealias $KEYSTOREALIAS \
                                  --keystorealiaspass "$KEYSTOREALIAS_PASS" \
                                  --androidreleasetype APK
            mv android/app/build/outputs/apk/release/app-release-signed.apk repath-studio-android.apk
            npx cap build android --keystorepath official.jks \
                                  --keystorepass "$KEYSTORE_PASS" \
                                  --keystorealias $KEYSTOREALIAS \
                                  --keystorealiaspass "$KEYSTOREALIAS_PASS" \
                                  --androidreleasetype AAB
            mv android/app/build/outputs/bundle/release/app-release-signed.aab repath-studio-android.aab

      - name: Upload android apk to release
        uses: actions/upload-artifact@v5
        with:
          name: android-apk
          path: repath-studio-android.apk

      - name: Upload android aab to release
        uses: actions/upload-artifact@v5
        with:
          name: android-aab
          path: repath-studio-android.aab

      - name: Release android app
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON }}
          packageName: studio.repath.app
          releaseFiles: repath-studio-android.aab
          track: internal
          status: draft
